global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape cAdvisor running on EC2
  - job_name: "cadvisor-ec2"
    static_configs:
      - targets: ["3.135.0.171:8081"]
  - job_name: "nginx-dev"
    static_configs:
      - targets: ["3.135.0.171:9114"]
  - job_name: "nginx-prod"
    static_configs:
      - targets: ["3.135.0.171:9115"]
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
